export const CompaniesData = [
  { name: "Yelp", questions: 3, index: 1 },
  { name: "VMware", questions: 30, index: 2 },
  { name: "Apple", questions: 240, index: 3 },
  { name: "tcs", questions: 8, index: 4 },
  { name: "Opendoor", questions: 2, index: 5 },
  { name: "Thumbtack", questions: 1, index: 6 },
  { name: "IXL", questions: 2, index: 7 },
  { name: "Bloomberg", questions: 222, index: 8 },
  { name: "Two Sigma", questions: 4, index: 9 },
  { name: "Nuro", questions: 1, index: 10 },
  { name: "Flipkart", questions: 6, index: 11 },
  { name: "AllinCall", questions: 1, index: 12 },
  { name: "Zoom", questions: 5, index: 13 },
  { name: "HRT", questions: 6, index: 14 },
  { name: "Nutanix", questions: 3, index: 15 },
  { name: "ZScaler", questions: 1, index: 16 },
  { name: "Zopsmart", questions: 1, index: 17 },
  { name: "AppDynamics", questions: 1, index: 18 },
  { name: "Alibaba", questions: 2, index: 19 },
  { name: "Oracle", questions: 84, index: 20 },
  { name: "Citrix", questions: 1, index: 21 },
  { name: "Moengage", questions: 1, index: 22 },
  { name: "PhonePe", questions: 2, index: 23 },
  { name: "Grab", questions: 7, index: 24 },
  { name: "Hulu", questions: 1, index: 25 },
  { name: "Akuna Capital", questions: 1, index: 26 },
  { name: "Zomato", questions: 1, index: 27 },
  { name: "Affirm", questions: 6, index: 28 },
  { name: "Paypal", questions: 11, index: 29 },
  { name: "PayTM", questions: 3, index: 30 },
  { name: "Directi", questions: 1, index: 31 },
  { name: "JP Morgan", questions: 2, index: 32 },
  { name: "Mathworks", questions: 6, index: 33 },
  { name: "Wayfair", questions: 11, index: 34 },
  { name: "Yahoo", questions: 42, index: 35 },
  { name: "ServiceNow", questions: 13, index: 36 },
  { name: "Cognizant", questions: 1, index: 37 },
  { name: "Deutsche Bank", questions: 2, index: 38 },
  { name: "zeta suite", questions: 1, index: 39 },
  { name: "Rakuten", questions: 1, index: 40 },
  { name: "Tesla", questions: 9, index: 41 },
  { name: "Sony", questions: 1, index: 42 },
  { name: "eBay", questions: 9, index: 43 },
  { name: "Square", questions: 9, index: 44 },
  { name: "FPT", questions: 1, index: 45 },
  { name: "Epic Systems", questions: 3, index: 46 },
  { name: "Cashfree", questions: 1, index: 47 },
  { name: "Qualcomm", questions: 3, index: 48 },
  { name: "Wish", questions: 1, index: 49 },
  { name: "Twitter", questions: 27, index: 50 },
  { name: "Canonical", questions: 1, index: 51 },
  { name: "Nvidia", questions: 21, index: 52 },
  { name: "Rupeek", questions: 1, index: 53 },
  { name: "IMC", questions: 1, index: 54 },
  { name: "Huawei", questions: 1, index: 55 },
  { name: "Cohesity", questions: 1, index: 56 },
  { name: "Commvault", questions: 1, index: 57 },
  { name: "GoDaddy", questions: 2, index: 58 },
  { name: "Sapient", questions: 1, index: 59 },
  { name: "Amazon", questions: 592, index: 60 },
  { name: "Dataminr", questions: 1, index: 61 },
  { name: "MAQ Software", questions: 1, index: 62 },
  { name: "Pure Storage", questions: 2, index: 63 },
  { name: "Dell", questions: 1, index: 64 },
  { name: "MindTree", questions: 1, index: 65 },
  { name: "Zillow", questions: 2, index: 66 },
  { name: "Morgan Stanley", questions: 7, index: 67 },
  { name: "Valve", questions: 1, index: 68 },
  { name: "DJI", questions: 1, index: 69 },
  { name: "Bolt", questions: 5, index: 70 },
  { name: "Snapchat", questions: 38, index: 71 },
  { name: "Dunzo", questions: 4, index: 72 },
  { name: "Samsung", questions: 7, index: 73 },
  { name: "Athenahealth", questions: 1, index: 74 },
  { name: "Coursera", questions: 2, index: 75 },
  { name: "Jane Street", questions: 1, index: 76 },
  { name: "JPMorgan", questions: 16, index: 77 },
  { name: "Citadel", questions: 6, index: 78 },
  { name: "Druva", questions: 1, index: 79 },
  { name: "Mercari", questions: 4, index: 80 },
  { name: "Sprinklr", questions: 5, index: 81 },
  { name: "Visa", questions: 20, index: 82 },
  { name: "IBM", questions: 10, index: 83 },
  { name: "IIT Bombay", questions: 1, index: 84 },
  { name: "United Health Group", questions: 2, index: 85 },
  { name: "Barclays", questions: 1, index: 86 },
  { name: "Alation", questions: 3, index: 87 },
  { name: "Pocket Gems", questions: 1, index: 88 },
  { name: "TIAA", questions: 1, index: 89 },
  { name: "Dropbox", questions: 6, index: 90 },
  { name: "Google", questions: 488, index: 91 },
  { name: "Capital One", questions: 10, index: 92 },
  { name: "T System", questions: 1, index: 93 },
  { name: "Sumologic", questions: 4, index: 94 },
  { name: "Shopee", questions: 9, index: 95 },
  { name: "Optum", questions: 1, index: 96 },
  { name: "Arcesium", questions: 3, index: 97 },
  { name: "APT Portfolio", questions: 1, index: 98 },
  { name: "Yandex", questions: 21, index: 99 },
  { name: "Docusign", questions: 7, index: 100 },
  { name: "Redfin", questions: 2, index: 101 },
  { name: "Accenture", questions: 5, index: 102 },
  { name: "National Instruments", questions: 1, index: 103 },
  { name: "edabit", questions: 1, index: 104 },
  { name: "OT", questions: 1, index: 105 },
  { name: "FactSet", questions: 1, index: 106 },
  { name: "LiveRamp", questions: 4, index: 107 },
  { name: "Lyft", questions: 10, index: 108 },
  { name: "Reddit", questions: 3, index: 109 },
  { name: "Zenefits", questions: 2, index: 110 },
  { name: "Databricks", questions: 3, index: 111 },
  { name: "HBO", questions: 2, index: 112 },
  { name: "Microsoft", questions: 363, index: 113 },
  { name: "Leap Motion", questions: 1, index: 114 },
  { name: "TuSimple", questions: 3, index: 115 },
  { name: "Cruise Automation", questions: 9, index: 116 },
  { name: "Splunk", questions: 1, index: 117 },
  { name: "Expedia", questions: 20, index: 118 },
  { name: "BlackRock", questions: 2, index: 119 },
  { name: "Uber", questions: 129, index: 120 },
  { name: "ByteDance", questions: 42, index: 121 },
  { name: "MindTickle", questions: 1, index: 122 },
  { name: "Riot Games", questions: 1, index: 123 },
  { name: "Honeywell", questions: 1, index: 124 },
  { name: "Quora", questions: 7, index: 125 },
  { name: "SAP", questions: 7, index: 126 },
  { name: "Intuit", questions: 13, index: 127 },
  { name: "Tiger Analytics", questions: 1, index: 128 },
  { name: "Gilt Groupe", questions: 1, index: 129 },
  { name: "Twitch", questions: 2, index: 130 },
  { name: "Robinhood", questions: 4, index: 131 },
  { name: "Postmates", questions: 3, index: 132 },
  { name: "Spotify", questions: 14, index: 133 },
  { name: "Indeed", questions: 10, index: 134 },
  { name: "Karat", questions: 13, index: 135 },
  { name: "Toptal", questions: 1, index: 136 },
  { name: "Facebook", questions: 371, index: 137 },
  { name: "Airbnb", questions: 15, index: 138 },
  { name: "Softwire", questions: 1, index: 139 },
  { name: "Adobe", questions: 188, index: 140 },
  { name: "instacart", questions: 1, index: 141 },
  { name: "Info Edge", questions: 1, index: 142 },
  { name: "American Express", questions: 5, index: 143 },
  { name: "Box", questions: 2, index: 144 },
  { name: "TripleByte", questions: 1, index: 145 },
  { name: "Walmart Global Tech", questions: 36, index: 146 },
  { name: "Infosys", questions: 6, index: 147 },
  { name: "Rubrik", questions: 8, index: 148 },
  { name: "Akamai", questions: 1, index: 149 },
  { name: "LinkedIn", questions: 92, index: 150 },
  { name: "persistent systems", questions: 1, index: 151 },
  { name: "payu", questions: 2, index: 152 },
  { name: "DRW", questions: 2, index: 153 },
  { name: "Drawbridge", questions: 1, index: 154 },
  { name: "Activision", questions: 1, index: 155 },
  { name: "Goldman Sachs", questions: 63, index: 156 },
  { name: "Tencent", questions: 1, index: 157 },
  { name: "Asana", questions: 2, index: 158 },
  { name: "Swiggy", questions: 3, index: 159 },
  { name: "Cisco", questions: 24, index: 160 },
  { name: "Jeavio", questions: 1, index: 161 },
  { name: "C3 IoT", questions: 4, index: 162 },
  { name: "Duolingo", questions: 1, index: 163 },
  { name: "Netflix", questions: 5, index: 164 },
  { name: "MakeMyTrip", questions: 2, index: 165 },
  { name: "Netsuite", questions: 1, index: 166 },
  { name: "Arista Networks", questions: 4, index: 167 },
  { name: "Wealthfront", questions: 1, index: 168 },
  { name: "DE Shaw", questions: 3, index: 169 },
  { name: "DoorDash", questions: 25, index: 170 },
  { name: "Roblox", questions: 5, index: 171 },
  { name: "Salesforce", questions: 47, index: 172 },
  { name: "Booking", questions: 7, index: 173 },
  { name: "peak6", questions: 1, index: 174 },
  { name: "tiktok", questions: 62, index: 175 },
  { name: "Palantir Technologies", questions: 2, index: 176 },
  { name: "Virtu Financial", questions: 5, index: 177 },
  { name: "Baidu", questions: 3, index: 178 },
  { name: "Hotstar", questions: 3, index: 179 },
  { name: "Twilio", questions: 9, index: 180 },
  { name: "Atlassian", questions: 7, index: 181 },
  { name: "Qualtrics", questions: 15, index: 182 },
  { name: "Pinterest", questions: 7, index: 183 },
  { name: "Intel", questions: 5, index: 184 },
  { name: "Zoho", questions: 5, index: 185 },
  { name: "razorpay", questions: 1, index: 186 },
  { name: "Works Applications", questions: 1, index: 187 },
];
